from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^login/$', 'nutricionApp.views.log_in'),
    url(r'^login/auth/$', 'nutricionApp.views.auth_view'),
    url(r'^error_login/$', 'nutricionApp.views.error_login'),
    url(r'^logout/$', 'nutricionApp.views.log_out'),
#de aca pa alla ya estaba
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'nutricionApp.views.home'),
    url(r'^alimentos$', 'nutricionApp.views.listar_alimentos'),
    url(r'^porciones$', 'nutricionApp.views.listar_porciones'),
    url(r'^nutrientes$', 'nutricionApp.views.listar_nutrientes'),
    url(r'^etiquetas$', 'nutricionApp.views.listar_etiquetas'),
    url(r'^reglas$', 'nutricionApp.views.listar_reglas'),
    url(r'^recomendaciones$', 'nutricionApp.views.listar_recomendaciones'),
    url(r'^etiquetas/([A-Za-z]{1,20})/$', 'nutricionApp.views.listar_etiquetasNutriente'),
    url(r'^alimento/(\d{1,5})/$', 'nutricionApp.views.listar_nutrientesAlimento'),
    url(r'^guardar_alimentos/$', 'nutricionApp.views.guardar_alimentos'),
    url(r'^guardar_reglas/$', 'nutricionApp.views.guardar_reglas'),
    url(r'^guardar_porciones/$', 'nutricionApp.views.guardar_porciones'),
    url(r'^guardar_funciones/$', 'nutricionApp.views.guardar_funciones'),
    url(r'^guardar_nutrientes/$', 'nutricionApp.views.guardar_nutrientes'),
    url(r'^guardar_etiquetas/$', 'nutricionApp.views.guardar_etiquetas'),
    url(r'^guardar_recomendaciones/$', 'nutricionApp.views.guardar_recomendaciones'),
    url(r'^guardar_nutrientesAlimento/$', 'nutricionApp.views.guardar_nutrientesAlimento'),
    url(r'^guardar_nuevo_etiqueta_nutriente/$', 'nutricionApp.views.guardar_nuevo_etiqueta_nutriente'),
    url(r'^guardar_nueva_regla/$', 'nutricionApp.views.guardar_nueva_regla'),
    url(r'^guardar_nuevo_nutriente/$', 'nutricionApp.views.guardar_nuevo_nutriente'),
    url(r'^guardar_nueva_etiqueta/$', 'nutricionApp.views.guardar_nueva_etiqueta'),
    url(r'^guardar_nueva_recomendacion/$', 'nutricionApp.views.guardar_nueva_recomendacion'),
    url(r'^guardar_nueva_porcion/$', 'nutricionApp.views.guardar_nueva_porcion'),
    url(r'^guardar_nuevo_alimento/$', 'nutricionApp.views.guardar_nuevo_alimento'),
    url(r'^guardar_nuevo_nutrientesAlimento/$', 'nutricionApp.views.guardar_nuevo_nutrientesAlimento'),
    url(r'^eliminar_nutriente_etiqueta/$', 'nutricionApp.views.eliminar_nutriente_etiqueta'),
    url(r'^eliminar_etiqueta/$', 'nutricionApp.views.eliminar_etiqueta'),
    url(r'^eliminar_recomendacion/$', 'nutricionApp.views.eliminar_recomendacion'),
    url(r'^eliminar_nutriente/$', 'nutricionApp.views.eliminar_nutriente'),
    url(r'^eliminar_alimento/$', 'nutricionApp.views.eliminar_alimento'),
    url(r'^eliminar_porcion/$', 'nutricionApp.views.eliminar_porcion'),
    url(r'^eliminar_funcion/$', 'nutricionApp.views.eliminar_funcion'),
    url(r'^eliminar_regla/$', 'nutricionApp.views.eliminar_regla'),
    url(r'^eliminar_nutrientesAlimento/$', 'nutricionApp.views.eliminar_nutrientesAlimento'),
    url(r'^database/odata/$', 'nutricionApp.views.get_data'),
    url(r'^api/$', 'nutricionApp.views.api_op'),


]
